export global Logic {
    //rust переменные
    in-out property <string> button_play_status;
    in-out property <string> username;
    in-out property <string> password;
    in-out property <string> login_information_output: "test huita";


    //callback
    callback play_minecrat_process;
}

export global Color {
    //rust переменные
    in-out property <color> button_play;

    //slint переменные
    in-out property <color> background: #151515;
    in-out property <color> primary: #008E45;
    in-out property <color> error: #FF6363;
    in-out property <color> qwer: #969696;
}

export global Enabled {
    //rust переменные
    in-out property <bool> global_button: true;
    in-out property <bool> button_play: true;

    //slint переменные
    in-out property <bool> all_settings_button;
    in-out property <bool> all_auth_button;


}