import { Logic, Color, Enabled} from "logic.slint";
import { Button } from "std-widgets.slint";


export component Settings  inherits Rectangle{
    z: 5;
    width: 720px;
    height: 480px;

    opacity: Enabled.all_settings_button ? 1.0 : 0.0;
    animate opacity {duration: 200ms; easing: ease-in-out;}
    Rectangle {
        width: 1005px;
        height: 563px;
        background: Color.background;
        opacity: 0.75;
    }
    Rectangle {
        background: Color.background;
        border-radius: 20px;
        border-color: Color.primary;
        border-width: 0.5px;
    }

    Rectangle {
        x:580px; y:40px;
        width: 100px;
        height: 40px;
        background: Color.background;
        border-radius: 20px;
        clip: true;


        Text{
            text:"Назад";
            font-size: 14px;
            font-family: "Inter";
            font-weight: FontWeight.bold;
        }

        Button{
            width: 100%;
            height: 100%;
            enabled: Enabled.all_settings_button;
            clicked => {
                Enabled.all_settings_button = false;
                Enabled.global_button = true;
            }
        }
    }
}




